-- Seed for brand/line/colors

INSERT OR IGNORE INTO brand (id, slug, name) VALUES ('generic', 'generic', 'Generic');
INSERT OR IGNORE INTO line (id, brand_id, slug, name) VALUES ('generic:default', 'generic', 'default', 'Default');



INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:01', 'generic:default', '01', '01', 'White Tin', '#E3E3E6', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:02', 'generic:default', '02', '02', 'Tin', '#D7D7D8', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:03', 'generic:default', '03', '03', 'Tin Medium', '#B8B8BB', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:04', 'generic:default', '04', '04', 'Tin Dark', '#AEAEB1', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:05', 'generic:default', '05', '05', 'Driftwood Light', '#E3CCBE', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:06', 'generic:default', '06', '06', 'Driftwood Medium Light', '#DCC6B8', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:07', 'generic:default', '07', '07', 'Driftwood', '#8F7B6E', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:08', 'generic:default', '08', '08', 'Driftwood Dark', '#6A5046', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:09', 'generic:default', '09', '09', 'Cocoa Very Dark', '#552014', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:10', 'generic:default', '10', '10', 'Tender Green Very Light', '#EDFED9', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:11', 'generic:default', '11', '11', 'Tender Green Light', '#E2EDB5', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:12', 'generic:default', '12', '12', 'Tender Green', '#CDD99A', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:13', 'generic:default', '13', '13', 'Nile Green Medium Light', '#BFF6E0', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:14', 'generic:default', '14', '14', 'Apple Green Pale', '#D0FBB2', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:15', 'generic:default', '15', '15', 'Apple Green', '#D1EDA4', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:16', 'generic:default', '16', '16', 'Chartreuse Light', '#C9C258', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:17', 'generic:default', '17', '17', 'Yellow Plum Light', '#E5E272', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:18', 'generic:default', '18', '18', 'Yellow Plum', '#D9D56D', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:19', 'generic:default', '19', '19', 'Autumn Gold medium Light', '#F7C95F', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:20', 'generic:default', '20', '20', 'Shrimp', '#F7AF93', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:21', 'generic:default', '21', '21', 'Alizarin Light', '#D79982', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:22', 'generic:default', '22', '22', 'Alizarin', '#BC604E', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:23', 'generic:default', '23', '23', 'Apple Blossom', '#EDE2ED', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:24', 'generic:default', '24', '24', 'White Lavender', '#E0D7EE', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:25', 'generic:default', '25', '25', 'Lavender Ultra Light', '#DAD2E9', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:26', 'generic:default', '26', '26', 'Lavender Pale', '#D7CAE6', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:27', 'generic:default', '27', '27', 'White Violet', '#F0EEF9', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:28', 'generic:default', '28', '28', 'Eggplant Medium Light', '#9086A9', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:29', 'generic:default', '29', '29', 'Eggplant', '#674076', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:30', 'generic:default', '30', '30', 'Blueberry Medium Light', '#7D77A5', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:31', 'generic:default', '31', '31', 'Blueberry', '#50518D', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:32', 'generic:default', '32', '32', 'Blueberry Dark', '#4D2E8A', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:33', 'generic:default', '33', '33', 'Fuschia', '#9C599C', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:34', 'generic:default', '34', '34', 'Fuschia Dark', '#7D3064', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:35', 'generic:default', '35', '35', 'Fuschia Very Dark', '#46052D', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:150', 'generic:default', '150', '150', 'Dusty Rose Ultra Very Dark', '#AB0249', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:151', 'generic:default', '151', '151', 'Dusty Rose Very Light', '#F0CED4', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:152', 'generic:default', '152', '152', 'Shell Pink Medium Light', '#E2A099', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:153', 'generic:default', '153', '153', 'Violet Very Light', '#E6CCD9', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:154', 'generic:default', '154', '154', 'Grape Very Dark', '#572433', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:155', 'generic:default', '155', '155', 'Blue Violet Medium Dark', '#9891B6', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:156', 'generic:default', '156', '156', 'Blue Violet Medium Light', '#A3AED1', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:157', 'generic:default', '157', '157', 'Cornflower Blue Very Light', '#BBC3D9', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:158', 'generic:default', '158', '158', 'Cornflower Blue Very Dark', '#4C526E', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:159', 'generic:default', '159', '159', 'Blue Gray Light', '#C7CAD7', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:160', 'generic:default', '160', '160', 'Blue Gray Medium', '#999FB7', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:161', 'generic:default', '161', '161', 'Blue Gray', '#7880A4', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:162', 'generic:default', '162', '162', 'Blue Ultra Very Light', '#DBECF5', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:163', 'generic:default', '163', '163', 'Celadon Green Medium', '#4D8361', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:164', 'generic:default', '164', '164', 'Forest Green Light', '#C8D8B8', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:165', 'generic:default', '165', '165', 'Moss Green Very Light', '#EFF4A4', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:166', 'generic:default', '166', '166', 'Moss Green Medium Light', '#C0C840', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:167', 'generic:default', '167', '167', 'Yellow Beige Very Dark', '#A77C49', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:168', 'generic:default', '168', '168', 'Pewter Very Light', '#D1D1D1', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:169', 'generic:default', '169', '169', 'Pewter Light', '#848484', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:208', 'generic:default', '208', '208', 'Lavender Very Dark', '#835B8B', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:209', 'generic:default', '209', '209', 'Lavender Dark', '#A37BA7', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:210', 'generic:default', '210', '210', 'Lavender Medium', '#D29FC3', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:211', 'generic:default', '211', '211', 'Lavender Light', '#E3CBE3', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:221', 'generic:default', '221', '221', 'Shell Pink Very Dark', '#883E43', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:223', 'generic:default', '223', '223', 'Shell Pink Light', '#CC847C', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:224', 'generic:default', '224', '224', 'Shell Pink Very Light', '#EBB7AF', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:225', 'generic:default', '225', '225', 'Shell Pink Ultra Very Light', '#FFDFD7', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:300', 'generic:default', '300', '300', 'Mahogany Very Dark', '#6F2F00', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:301', 'generic:default', '301', '301', 'Mahogany Medium', '#B35F2B', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:304', 'generic:default', '304', '304', 'Red Medium', '#B71F33', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:307', 'generic:default', '307', '307', 'Lemon', '#FDED54', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:309', 'generic:default', '309', '309', 'Rose Dark', '#BA4A4A', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:310', 'generic:default', '310', '310', 'Black', '#000000', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:311', 'generic:default', '311', '311', 'Wedgewood Ultra Very Dark', '#1C5066', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:312', 'generic:default', '312', '312', 'Baby Blue Very Dark', '#35668B', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:315', 'generic:default', '315', '315', 'Antique Mauve Medium Dark', '#814952', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:316', 'generic:default', '316', '316', 'Antique Mauve Medium', '#B7737F', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:317', 'generic:default', '317', '317', 'Pewter Gray', '#6C6C6C', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:318', 'generic:default', '318', '318', 'Steel Gray Light', '#ABABAB', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:319', 'generic:default', '319', '319', 'Pistachio Grn Very Dark', '#205F2E', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:320', 'generic:default', '320', '320', 'Pistachio Green Medium', '#69885A', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:321', 'generic:default', '321', '321', 'Red', '#C72B3B', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:322', 'generic:default', '322', '322', 'Baby Blue Dark', '#5A8FB8', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:326', 'generic:default', '326', '326', 'Rose Very Dark', '#B33B4B', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:327', 'generic:default', '327', '327', 'Violet Dark', '#633666', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:333', 'generic:default', '333', '333', 'Blue Violet Very Dark', '#5C5478', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:334', 'generic:default', '334', '334', 'Baby Blue Medium', '#739FC1', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:335', 'generic:default', '335', '335', 'Rose', '#EE546E', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:336', 'generic:default', '336', '336', 'Navy Blue', '#253B73', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:340', 'generic:default', '340', '340', 'Blue Violet Medium', '#ADA7C7', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:341', 'generic:default', '341', '341', 'Blue Violet Light', '#B7BFDD', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:347', 'generic:default', '347', '347', 'Salmon Very Dark', '#BF2D2D', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:349', 'generic:default', '349', '349', 'Coral Dark', '#D21035', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:350', 'generic:default', '350', '350', 'Coral Medium', '#E04848', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:351', 'generic:default', '351', '351', 'Coral', '#E96A67', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:352', 'generic:default', '352', '352', 'Coral Light', '#FD9C97', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:353', 'generic:default', '353', '353', 'Peach', '#FED7CC', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:355', 'generic:default', '355', '355', 'Terra Cotta Dark', '#984436', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:356', 'generic:default', '356', '356', 'Terra Cotta Medium', '#C56A5B', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:367', 'generic:default', '367', '367', 'Pistachio Green Dark', '#617A52', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:368', 'generic:default', '368', '368', 'Pistachio Green Light', '#A6C298', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:369', 'generic:default', '369', '369', 'Pistachio Green Very Light', '#D7EDCC', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:370', 'generic:default', '370', '370', 'Mustard Medium', '#B89D64', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:371', 'generic:default', '371', '371', 'Mustard', '#BFA671', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:372', 'generic:default', '372', '372', 'Mustard Light', '#CCB784', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:400', 'generic:default', '400', '400', 'Mahogany Dark', '#8F430F', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:402', 'generic:default', '402', '402', 'Mahogany Very Light', '#F7A777', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:407', 'generic:default', '407', '407', 'Desert Sand Medium', '#BB8161', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:413', 'generic:default', '413', '413', 'Pewter Gray Dark', '#565656', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:414', 'generic:default', '414', '414', 'Steel Gray Dark', '#8C8C8C', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:415', 'generic:default', '415', '415', 'Pearl Gray', '#D3D3D6', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:420', 'generic:default', '420', '420', 'Hazelnut Brown Dark', '#A07042', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:422', 'generic:default', '422', '422', 'Hazelnut Brown Light', '#C69F7B', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:433', 'generic:default', '433', '433', 'Brown Medium', '#7A451F', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:434', 'generic:default', '434', '434', 'Brown Light', '#985E33', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:435', 'generic:default', '435', '435', 'Brown Very Light', '#B87748', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:436', 'generic:default', '436', '436', 'Tan', '#CB9051', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:437', 'generic:default', '437', '437', 'Tan Light', '#E4BB8E', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:444', 'generic:default', '444', '444', 'Lemon Dark', '#FFD600', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:445', 'generic:default', '445', '445', 'Lemon Light', '#FFFB8B', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:451', 'generic:default', '451', '451', 'Shell Gray Dark', '#917B73', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:452', 'generic:default', '452', '452', 'Shell Gray Medium', '#C0B3AE', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:453', 'generic:default', '453', '453', 'Shell Gray Light', '#D7CECB', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:469', 'generic:default', '469', '469', 'Avocado Green', '#72843C', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:470', 'generic:default', '470', '470', 'Avocado Grn Light', '#94AB4F', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:471', 'generic:default', '471', '471', 'Avocado Grn Very Light', '#AEBF79', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:472', 'generic:default', '472', '472', 'Avocado Green Ultra Light', '#D8E498', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:498', 'generic:default', '498', '498', 'Red Dark', '#A7132B', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:500', 'generic:default', '500', '500', 'Blue Green Very Dark', '#044D33', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:501', 'generic:default', '501', '501', 'Blue Green Dark', '#396F52', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:502', 'generic:default', '502', '502', 'Blue Green', '#5B9071', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:503', 'generic:default', '503', '503', 'Blue Green Medium', '#7BAC94', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:504', 'generic:default', '504', '504', 'Blue Green Very Light', '#C4DECC', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:505', 'generic:default', '505', '505', 'Jade Green', '#338362', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:517', 'generic:default', '517', '517', 'Wedgewood Dark', '#3B768F', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:518', 'generic:default', '518', '518', 'Wedgewood Light', '#4F93A7', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:519', 'generic:default', '519', '519', 'Sky Blue', '#7EB1C8', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:520', 'generic:default', '520', '520', 'Fern Green Dark', '#666D4F', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:522', 'generic:default', '522', '522', 'Fern Green', '#969E7E', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:523', 'generic:default', '523', '523', 'Fern Green Light', '#ABB197', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:524', 'generic:default', '524', '524', 'Fern Green Very Light', '#C4CDAC', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:535', 'generic:default', '535', '535', 'Ash Gray Very Light', '#636458', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:543', 'generic:default', '543', '543', 'Beige Brown Ultra Very Light', '#F2E3CE', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:550', 'generic:default', '550', '550', 'Violet Very Dark', '#5C184E', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:552', 'generic:default', '552', '552', 'Violet Medium', '#803A6B', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:553', 'generic:default', '553', '553', 'Violet', '#A3638B', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:554', 'generic:default', '554', '554', 'Violet Light', '#DBB3CB', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:561', 'generic:default', '561', '561', 'Celadon Green VD', '#2C6A45', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:562', 'generic:default', '562', '562', 'Jade Medium', '#53976A', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:563', 'generic:default', '563', '563', 'Jade Light', '#8FC098', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:564', 'generic:default', '564', '564', 'Jade Very Light', '#A7CDAF', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:580', 'generic:default', '580', '580', 'Moss Green Dark', '#888D33', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:581', 'generic:default', '581', '581', 'Moss Green', '#A7AE38', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:597', 'generic:default', '597', '597', 'Turquoise', '#5BA3B3', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:598', 'generic:default', '598', '598', 'Turquoise Light', '#90C3CC', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:600', 'generic:default', '600', '600', 'Cranberry Very Dark', '#CD2F63', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:601', 'generic:default', '601', '601', 'Cranberry Dark', '#D1286A', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:602', 'generic:default', '602', '602', 'Cranberry Medium', '#E24874', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:603', 'generic:default', '603', '603', 'Cranberry', '#FFA4BE', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:604', 'generic:default', '604', '604', 'Cranberry Light', '#FFB0BE', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:605', 'generic:default', '605', '605', 'Cranberry Very Light', '#FFC0CD', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:606', 'generic:default', '606', '606', 'Orange Red Bright', '#FA3203', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:608', 'generic:default', '608', '608', 'Burnt Orange Bright', '#FD5D35', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:610', 'generic:default', '610', '610', 'Drab Brown Dark', '#796047', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:611', 'generic:default', '611', '611', 'Drab Brown', '#967656', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:612', 'generic:default', '612', '612', 'Drab Brown Light', '#BC9A78', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:613', 'generic:default', '613', '613', 'Drab Brown Very Light', '#DCC4AA', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:632', 'generic:default', '632', '632', 'Desert Sand Ultra Very Dark', '#875539', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:640', 'generic:default', '640', '640', 'Beige Gray Very Dark', '#857B61', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:642', 'generic:default', '642', '642', 'Beige Gray Dark', '#A49878', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:644', 'generic:default', '644', '644', 'Beige Gray Medium', '#DDD8CB', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:645', 'generic:default', '645', '645', 'Beaver Gray Very Dark', '#6E655C', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:646', 'generic:default', '646', '646', 'Beaver Gray Dark', '#877D73', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:647', 'generic:default', '647', '647', 'Beaver Gray Medium', '#B0A69C', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:648', 'generic:default', '648', '648', 'Beaver Gray Light', '#BCB4AC', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:666', 'generic:default', '666', '666', 'Bright Red', '#E31D42', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:676', 'generic:default', '676', '676', 'Old Gold Light', '#E5CE97', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:677', 'generic:default', '677', '677', 'Old Gold Very Light', '#F5ECCB', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:680', 'generic:default', '680', '680', 'Old Gold Dark', '#BC8D0E', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:699', 'generic:default', '699', '699', 'Green', '#056517', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:700', 'generic:default', '700', '700', 'Green Bright', '#07731B', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:701', 'generic:default', '701', '701', 'Green Light', '#3F8F29', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:702', 'generic:default', '702', '702', 'Kelly Green', '#47A72F', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:703', 'generic:default', '703', '703', 'Chartreuse', '#7BB547', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:704', 'generic:default', '704', '704', 'Chartreuse Bright', '#9ECF34', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:712', 'generic:default', '712', '712', 'Cream', '#FFFBEF', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:718', 'generic:default', '718', '718', 'Plum', '#9C2462', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:720', 'generic:default', '720', '720', 'Orange Spice Dark', '#E55C1F', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:721', 'generic:default', '721', '721', 'Orange Spice Medium', '#F27842', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:722', 'generic:default', '722', '722', 'Orange Spice Light', '#F7976F', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:725', 'generic:default', '725', '725', 'Topaz Medium Light', '#FFC840', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:726', 'generic:default', '726', '726', 'Topaz Light', '#FDD755', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:727', 'generic:default', '727', '727', 'Topaz Very Light', '#FFF1AF', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:728', 'generic:default', '728', '728', 'Topaz', '#E4B468', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:729', 'generic:default', '729', '729', 'Old Gold Medium', '#D0A53E', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:730', 'generic:default', '730', '730', 'Olive Green Very Dark', '#827B30', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:731', 'generic:default', '731', '731', 'Olive Green Dark', '#938B37', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:732', 'generic:default', '732', '732', 'Olive Green', '#948C36', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:733', 'generic:default', '733', '733', 'Olive Green Medium', '#BCB34C', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:734', 'generic:default', '734', '734', 'Olive Green Light', '#C7C077', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:738', 'generic:default', '738', '738', 'Tan Very Light', '#ECCC9E', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:739', 'generic:default', '739', '739', 'Tan Ultra Very Light', '#F8E4C8', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:740', 'generic:default', '740', '740', 'Tangerine', '#FF8B00', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:741', 'generic:default', '741', '741', 'Tangerine Medium', '#FFA32B', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:742', 'generic:default', '742', '742', 'Tangerine Light', '#FFBF57', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:743', 'generic:default', '743', '743', 'Yellow Medium', '#FED376', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:744', 'generic:default', '744', '744', 'Yellow Pale', '#FFE793', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:745', 'generic:default', '745', '745', 'Yellow Pale Light', '#FFE9AD', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:746', 'generic:default', '746', '746', 'Off White', '#FCFCEE', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:747', 'generic:default', '747', '747', 'Peacock Blue Very Light', '#E5FCFD', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:754', 'generic:default', '754', '754', 'Peach Light', '#F7CBBF', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:758', 'generic:default', '758', '758', 'Terra Cotta Very Light', '#EEAA9B', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:760', 'generic:default', '760', '760', 'Salmon', '#F5ADAD', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:761', 'generic:default', '761', '761', 'Salmon Light', '#FFC9C9', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:762', 'generic:default', '762', '762', 'Pearl Gray Very Light', '#ECECEC', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:772', 'generic:default', '772', '772', 'Yellow Green Very Light', '#E4ECD4', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:775', 'generic:default', '775', '775', 'Baby Blue Very Light', '#D9EBF1', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:776', 'generic:default', '776', '776', 'Pink Medium', '#FCB0B9', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:777', 'generic:default', '777', '777', 'Raspberry Very Dark', '#913546', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:778', 'generic:default', '778', '778', 'Antique Mauve Very Light', '#DFB3BB', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:779', 'generic:default', '779', '779', 'Cocoa Dark', '#624B45', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:780', 'generic:default', '780', '780', 'Topaz Ultra Very Dark', '#94631A', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:781', 'generic:default', '781', '781', 'Topaz Very Dark', '#A26D20', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:782', 'generic:default', '782', '782', 'Topaz Dark', '#AE7720', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:783', 'generic:default', '783', '783', 'Topaz Medium', '#CE9124', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:791', 'generic:default', '791', '791', 'Cornflower Blue Very Dark', '#464563', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:792', 'generic:default', '792', '792', 'Cornflower Blue Dark', '#555B7B', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:793', 'generic:default', '793', '793', 'Cornflower Blue Medium', '#707DA2', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:794', 'generic:default', '794', '794', 'Cornflower Blue Light', '#8F9CC1', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:796', 'generic:default', '796', '796', 'Royal Blue Dark', '#11416D', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:797', 'generic:default', '797', '797', 'Royal Blue', '#13477D', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:798', 'generic:default', '798', '798', 'Delft Blue Dark', '#466A8E', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:799', 'generic:default', '799', '799', 'Delft Blue Medium', '#748EB6', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:800', 'generic:default', '800', '800', 'Delft Blue Pale', '#C0CCDE', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:801', 'generic:default', '801', '801', 'Coffee Brown Dark', '#653919', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:803', 'generic:default', '803', '803', 'Baby Blue Ultra Very Dark', '#2C597C', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:806', 'generic:default', '806', '806', 'Peacock Blue Dark', '#3D95A5', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:807', 'generic:default', '807', '807', 'Peacock Blue', '#64ABBA', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:809', 'generic:default', '809', '809', 'Delft Blue', '#94A8C6', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:813', 'generic:default', '813', '813', 'Blue Light', '#A1C2D7', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:814', 'generic:default', '814', '814', 'Garnet Dark', '#7B001B', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:815', 'generic:default', '815', '815', 'Garnet Medium', '#87071F', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:816', 'generic:default', '816', '816', 'Garnet', '#970B23', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:817', 'generic:default', '817', '817', 'Coral Red Very Dark', '#BB051F', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:818', 'generic:default', '818', '818', 'Baby Pink', '#FFDFD9', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:819', 'generic:default', '819', '819', 'Baby Pink Light', '#FFEEEB', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:820', 'generic:default', '820', '820', 'Royal Blue Very Dark', '#0E365C', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:822', 'generic:default', '822', '822', 'Beige Gray Light', '#E7E2D3', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:823', 'generic:default', '823', '823', 'Navy Blue Dark', '#213063', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:824', 'generic:default', '824', '824', 'Blue Very Dark', '#396987', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:825', 'generic:default', '825', '825', 'Blue Dark', '#4781A5', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:826', 'generic:default', '826', '826', 'Blue Medium', '#6B9EBF', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:827', 'generic:default', '827', '827', 'Blue Very Light', '#BDDDED', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:828', 'generic:default', '828', '828', 'Sky Blue Very Light', '#C5E8ED', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:829', 'generic:default', '829', '829', 'Golden Olive Very Dark', '#7E6B42', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:830', 'generic:default', '830', '830', 'Golden Olive Dark', '#8D784B', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:831', 'generic:default', '831', '831', 'Golden Olive Medium', '#AA8F56', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:832', 'generic:default', '832', '832', 'Golden Olive', '#BD9B51', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:833', 'generic:default', '833', '833', 'Golden Olive Light', '#C8AB6C', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:834', 'generic:default', '834', '834', 'Golden Olive Very Light', '#DBBE7F', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:838', 'generic:default', '838', '838', 'Beige Brown Very Dark', '#594937', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:839', 'generic:default', '839', '839', 'Beige Brown Dark', '#675541', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:840', 'generic:default', '840', '840', 'Beige Brown Medium', '#9A7C5C', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:841', 'generic:default', '841', '841', 'Beige Brown Light', '#B69B7E', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:842', 'generic:default', '842', '842', 'Beige Brown Very Light', '#D1BAA1', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:844', 'generic:default', '844', '844', 'Beaver Gray Ultra Dark', '#484848', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:869', 'generic:default', '869', '869', 'Hazelnut Brown Very Dark', '#835E39', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:890', 'generic:default', '890', '890', 'Pistachio Grn Ultra Very Dark', '#184923', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:891', 'generic:default', '891', '891', 'Carnation Dark', '#FF5773', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:892', 'generic:default', '892', '892', 'Carnation Medium', '#FF798C', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:893', 'generic:default', '893', '893', 'Carnation Light', '#FC90A2', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:894', 'generic:default', '894', '894', 'Carnation Very Light', '#FFB2BB', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:895', 'generic:default', '895', '895', 'Hunter Green Very Dark', '#1B5300', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:898', 'generic:default', '898', '898', 'Coffee Brown Very Dark', '#492A13', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:899', 'generic:default', '899', '899', 'Rose Medium', '#F27688', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:900', 'generic:default', '900', '900', 'Burnt Orange Dark', '#D15807', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:902', 'generic:default', '902', '902', 'Garnet Very Dark', '#822637', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:904', 'generic:default', '904', '904', 'Parrot Green Very Dark', '#557822', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:905', 'generic:default', '905', '905', 'Parrot Green Dark', '#628A28', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:906', 'generic:default', '906', '906', 'Parrot Green Medium', '#7FB335', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:907', 'generic:default', '907', '907', 'Parrot Green Light', '#C7E666', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:909', 'generic:default', '909', '909', 'Emerald Green Very Dark', '#156F49', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:910', 'generic:default', '910', '910', 'Emerald Green Dark', '#187E56', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:911', 'generic:default', '911', '911', 'Emerald Green Medium', '#189065', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:912', 'generic:default', '912', '912', 'Emerald Green Light', '#1B9D6B', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:913', 'generic:default', '913', '913', 'Nile Green Medium', '#6DAB77', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:915', 'generic:default', '915', '915', 'Plum Dark', '#820043', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:917', 'generic:default', '917', '917', 'Plum Medium', '#9B1359', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:918', 'generic:default', '918', '918', 'Red Copper Dark', '#82340A', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:919', 'generic:default', '919', '919', 'Red Copper', '#A64510', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:920', 'generic:default', '920', '920', 'Copper Medium', '#AC5414', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:921', 'generic:default', '921', '921', 'Copper', '#C66218', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:922', 'generic:default', '922', '922', 'Copper Light', '#E27323', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:924', 'generic:default', '924', '924', 'Gray Green Vy Dark', '#566A6A', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:926', 'generic:default', '926', '926', 'Gray Green Medium', '#98AEAE', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:927', 'generic:default', '927', '927', 'Gray Green Light', '#BDCBCB', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:928', 'generic:default', '928', '928', 'Gray Green Very Light', '#DDE3E3', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:930', 'generic:default', '930', '930', 'Antique Blue Dark', '#455C71', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:931', 'generic:default', '931', '931', 'Antique Blue Medium', '#6A859E', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:932', 'generic:default', '932', '932', 'Antique Blue Light', '#A2B5C6', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:934', 'generic:default', '934', '934', 'Avocado Grn Black', '#313919', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:935', 'generic:default', '935', '935', 'Avocado Green Dark', '#424D21', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:936', 'generic:default', '936', '936', 'Avocado Green Very Dark', '#4C5826', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:937', 'generic:default', '937', '937', 'Avocado Green Medium', '#627133', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:938', 'generic:default', '938', '938', 'Coffee Brown Ultra Dark', '#361F0E', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:939', 'generic:default', '939', '939', 'Navy Blue Very Dark', '#1B2853', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:943', 'generic:default', '943', '943', 'Green Bright Medium', '#3D9384', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:945', 'generic:default', '945', '945', 'Tawny', '#FBD5BB', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:946', 'generic:default', '946', '946', 'Burnt Orange Medium', '#EB6307', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:947', 'generic:default', '947', '947', 'Burnt Orange', '#FF7B4D', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:948', 'generic:default', '948', '948', 'Peach Very Light', '#FEE7DA', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:950', 'generic:default', '950', '950', 'Desert Sand Light', '#EED3C4', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:951', 'generic:default', '951', '951', 'Tawny Light', '#FFE2CF', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:954', 'generic:default', '954', '954', 'Nile Green', '#88BA91', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:955', 'generic:default', '955', '955', 'Nile Green Light', '#A2D6AD', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:956', 'generic:default', '956', '956', 'Geranium', '#FF9191', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:957', 'generic:default', '957', '957', 'Geranium Pale', '#FDB5B5', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:958', 'generic:default', '958', '958', 'Sea Green Dark', '#3EB6A1', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:959', 'generic:default', '959', '959', 'Sea Green Medium', '#59C7B4', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:961', 'generic:default', '961', '961', 'Dusty Rose Dark', '#CF7373', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:962', 'generic:default', '962', '962', 'Dusty Rose Medium', '#E68A8A', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:963', 'generic:default', '963', '963', 'Dusty Rose Ultra Very Light', '#FFD7D7', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:964', 'generic:default', '964', '964', 'Sea Green Light', '#A9E2D8', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:966', 'generic:default', '966', '966', 'Jade Ultra Very Light', '#B9D7C0', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:967', 'generic:default', '967', '967', 'Apricot Very Light', '#FFDED5', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:970', 'generic:default', '970', '970', 'Pumpkin Light', '#F78B13', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:971', 'generic:default', '971', '971', 'Pumpkin', '#F67F00', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:972', 'generic:default', '972', '972', 'Canary Deep', '#FFB515', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:973', 'generic:default', '973', '973', 'Canary Bright', '#FFE300', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:975', 'generic:default', '975', '975', 'Golden Brown Dark', '#914F12', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:976', 'generic:default', '976', '976', 'Golden Brown Medium', '#C28142', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:977', 'generic:default', '977', '977', 'Golden Brown Light', '#DC9C56', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:986', 'generic:default', '986', '986', 'Forest Green Very Dark', '#405230', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:987', 'generic:default', '987', '987', 'Forest Green Dark', '#587141', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:988', 'generic:default', '988', '988', 'Forest Green Medium', '#738B5B', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:989', 'generic:default', '989', '989', 'Forest Green', '#8DA675', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:991', 'generic:default', '991', '991', 'Aquamarine Dark', '#477B6E', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:992', 'generic:default', '992', '992', 'Aquamarine Light', '#6FAE9F', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:993', 'generic:default', '993', '993', 'Aquamarine Very Light', '#90C0B4', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:995', 'generic:default', '995', '995', 'Electric Blue Dark', '#2696B6', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:996', 'generic:default', '996', '996', 'Electric Blue Medium', '#30C2EC', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3011', 'generic:default', '3011', '3011', 'Khaki Green Dark', '#898A58', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3012', 'generic:default', '3012', '3012', 'Khaki Green Medium', '#A6A75D', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3013', 'generic:default', '3013', '3013', 'Khaki Green Light', '#B9B982', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3021', 'generic:default', '3021', '3021', 'Brown Gray Very Dark', '#4F4B41', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3022', 'generic:default', '3022', '3022', 'Brown Gray Medium', '#8E9078', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3023', 'generic:default', '3023', '3023', 'Brown Gray Light', '#B1AA97', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3024', 'generic:default', '3024', '3024', 'Brown Gray Very Light', '#EBEAE7', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3031', 'generic:default', '3031', '3031', 'Mocha Brown Very Dark', '#4B3C2A', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3032', 'generic:default', '3032', '3032', 'Mocha Brown Medium', '#B39F8B', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3033', 'generic:default', '3033', '3033', 'Mocha Brown Very Light', '#E3D8CC', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3041', 'generic:default', '3041', '3041', 'Antique Violet Medium', '#956F7C', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3042', 'generic:default', '3042', '3042', 'Antique Violet Light', '#B79DA7', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3045', 'generic:default', '3045', '3045', 'Yellow Beige Dark', '#BC966A', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3046', 'generic:default', '3046', '3046', 'Yellow Beige Medium', '#D8BC9A', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3047', 'generic:default', '3047', '3047', 'Yellow Beige Light', '#E7D6C1', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3051', 'generic:default', '3051', '3051', 'Green Gray Dark', '#5F6648', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3052', 'generic:default', '3052', '3052', 'Green Gray Medium', '#889268', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3053', 'generic:default', '3053', '3053', 'Green Gray', '#9CA482', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3064', 'generic:default', '3064', '3064', 'Desert Sand', '#C48E70', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3072', 'generic:default', '3072', '3072', 'Beaver Gray Very Light', '#E6E8E8', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3078', 'generic:default', '3078', '3078', 'Golden Yellow Very Light', '#FDF9CD', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3325', 'generic:default', '3325', '3325', 'Baby Blue Light', '#B8D2E6', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3326', 'generic:default', '3326', '3326', 'Rose Light', '#FBADB4', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3328', 'generic:default', '3328', '3328', 'Salmon Dark', '#E36D6D', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3340', 'generic:default', '3340', '3340', 'Apricot Medium', '#FF836F', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3341', 'generic:default', '3341', '3341', 'Apricot', '#FCAB98', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3345', 'generic:default', '3345', '3345', 'Hunter Green Dark', '#1B5915', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3346', 'generic:default', '3346', '3346', 'Hunter Green', '#406A3A', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3347', 'generic:default', '3347', '3347', 'Yellow Green Medium', '#71935C', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3348', 'generic:default', '3348', '3348', 'Yellow Green Light', '#CCD9B1', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3350', 'generic:default', '3350', '3350', 'Dusty Rose Ultra Dark', '#BC4365', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3354', 'generic:default', '3354', '3354', 'Dusty Rose Light', '#E4A6AC', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3362', 'generic:default', '3362', '3362', 'Pine Green Dark', '#5E6B47', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3363', 'generic:default', '3363', '3363', 'Pine Green Medium', '#728256', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3364', 'generic:default', '3364', '3364', 'Pine Green', '#83975F', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3371', 'generic:default', '3371', '3371', 'Black Brown', '#1E1108', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3607', 'generic:default', '3607', '3607', 'Plum Light', '#C54989', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3608', 'generic:default', '3608', '3608', 'Plum Very Light', '#EA9CC4', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3609', 'generic:default', '3609', '3609', 'Plum Ultra Light', '#F4AED7', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3685', 'generic:default', '3685', '3685', 'Mauve Very Dark', '#881531', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3687', 'generic:default', '3687', '3687', 'Mauve', '#C96B70', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3688', 'generic:default', '3688', '3688', 'Mauve Medium', '#E7A9AC', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3689', 'generic:default', '3689', '3689', 'Mauve Light', '#FBBFC2', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3705', 'generic:default', '3705', '3705', 'Melon Dark', '#FF7992', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3706', 'generic:default', '3706', '3706', 'Melon Medium', '#FFADBC', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3708', 'generic:default', '3708', '3708', 'Melon Light', '#FFCBD5', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3712', 'generic:default', '3712', '3712', 'Salmon Medium', '#F18787', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3713', 'generic:default', '3713', '3713', 'Salmon Very Light', '#FFE2E2', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3716', 'generic:default', '3716', '3716', 'Dusty Rose Medium Very Light', '#FFBDBD', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3721', 'generic:default', '3721', '3721', 'Shell Pink Dark', '#A14B51', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3722', 'generic:default', '3722', '3722', 'Shell Pink Medium', '#BC6C64', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3726', 'generic:default', '3726', '3726', 'Antique Mauve Dark', '#9B5B66', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3727', 'generic:default', '3727', '3727', 'Antique Mauve Light', '#DBA9B2', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3731', 'generic:default', '3731', '3731', 'Dusty Rose Very Dark', '#DA6783', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3733', 'generic:default', '3733', '3733', 'Dusty Rose', '#E8879B', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3740', 'generic:default', '3740', '3740', 'Antique Violet Dark', '#785762', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3743', 'generic:default', '3743', '3743', 'Antique Violet Very Light', '#D7CBD3', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3746', 'generic:default', '3746', '3746', 'Blue Violet Dark', '#776B98', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3747', 'generic:default', '3747', '3747', 'Blue Violet Very Light', '#D3D7ED', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3750', 'generic:default', '3750', '3750', 'Antique Blue Very Dark', '#384C5E', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3752', 'generic:default', '3752', '3752', 'Antique Blue Very Light', '#C7D1DB', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3753', 'generic:default', '3753', '3753', 'Antique Blue Ultra Very Light', '#DBE2E9', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3755', 'generic:default', '3755', '3755', 'Baby Blue', '#92B4CE', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3756', 'generic:default', '3756', '3756', 'Baby Blue Ultra Very Light', '#EEFCFC', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3760', 'generic:default', '3760', '3760', 'Wedgewood Medium', '#3E85A2', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3761', 'generic:default', '3761', '3761', 'Sky Blue Light', '#ACD8E2', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3765', 'generic:default', '3765', '3765', 'Peacock Blue Very Dark', '#347F8C', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3766', 'generic:default', '3766', '3766', 'Peacock Blue Light', '#99CFD9', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3768', 'generic:default', '3768', '3768', 'Gray Green Dark', '#657F7F', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3770', 'generic:default', '3770', '3770', 'Tawny Vy Light', '#FFEEE3', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3771', 'generic:default', '3771', '3771', 'Terra Cotta Ultra Very Light', '#F4BBA9', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3772', 'generic:default', '3772', '3772', 'Desert Sand Very Dark', '#A06C50', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3773', 'generic:default', '3773', '3773', 'Desert Sand Dark', '#B67552', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3774', 'generic:default', '3774', '3774', 'Desert Sand Very Light', '#F3E1D7', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3776', 'generic:default', '3776', '3776', 'Mahogany Light', '#CF7939', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3777', 'generic:default', '3777', '3777', 'Terra Cotta Very Dark', '#863022', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3778', 'generic:default', '3778', '3778', 'Terra Cotta Light', '#D98978', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3779', 'generic:default', '3779', '3779', 'Rosewood Ultra Very Light', '#F8CAC8', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3781', 'generic:default', '3781', '3781', 'Mocha Brown Dark', '#6B5743', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3782', 'generic:default', '3782', '3782', 'Mocha Brown Light', '#D2BCA6', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3787', 'generic:default', '3787', '3787', 'Brown Gray Dark', '#625D50', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3790', 'generic:default', '3790', '3790', 'Beige Gray Ultra Dark', '#7F6A55', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3799', 'generic:default', '3799', '3799', 'Pewter Gray Very Dark', '#424242', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3801', 'generic:default', '3801', '3801', 'Melon Very Dark', '#E74967', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3802', 'generic:default', '3802', '3802', 'Antique Mauve Very Darkv', '#714149', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3803', 'generic:default', '3803', '3803', 'Mauve Dark', '#AB3357', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3804', 'generic:default', '3804', '3804', 'Cyclamen Pink Dark', '#E02876', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3805', 'generic:default', '3805', '3805', 'Cyclamen Pink', '#F3478B', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3806', 'generic:default', '3806', '3806', 'Cyclamen Pink Light', '#FF8CAE', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3807', 'generic:default', '3807', '3807', 'Cornflower Blue', '#60678C', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3808', 'generic:default', '3808', '3808', 'Turquoise Ultra Very Dark', '#366970', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3809', 'generic:default', '3809', '3809', 'Turquoise Vy Dark', '#3F7C85', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3810', 'generic:default', '3810', '3810', 'Turquoise Dark', '#488E9A', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3811', 'generic:default', '3811', '3811', 'Turquoise Very Light', '#BCE3E6', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3812', 'generic:default', '3812', '3812', 'Sea Green Very Dark', '#2F8C84', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3813', 'generic:default', '3813', '3813', 'Blue Green Light', '#B2D4BD', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3814', 'generic:default', '3814', '3814', 'Aquamarine', '#508B7D', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3815', 'generic:default', '3815', '3815', 'Celadon Green Dark', '#477759', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3816', 'generic:default', '3816', '3816', 'Celadon Green', '#65A57D', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3817', 'generic:default', '3817', '3817', 'Celadon Green Light', '#99C3AA', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3818', 'generic:default', '3818', '3818', 'Emerald Green Ultra Very Dark', '#115A3B', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3819', 'generic:default', '3819', '3819', 'Moss Green Light', '#E0E868', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3820', 'generic:default', '3820', '3820', 'Straw Dark', '#DFB65F', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3821', 'generic:default', '3821', '3821', 'Straw', '#F3CE75', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3822', 'generic:default', '3822', '3822', 'Straw Light', '#F6DC98', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3823', 'generic:default', '3823', '3823', 'Yellow Ultra Pale', '#FFFDE3', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3824', 'generic:default', '3824', '3824', 'Apricot Light', '#FECDC2', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3825', 'generic:default', '3825', '3825', 'Pumpkin Pale', '#FDBD96', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3826', 'generic:default', '3826', '3826', 'Golden Brown', '#AD7239', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3827', 'generic:default', '3827', '3827', 'Golden Brown Pale', '#F7BB77', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3828', 'generic:default', '3828', '3828', 'Hazelnut Brown', '#B78B61', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3829', 'generic:default', '3829', '3829', 'Old Gold Vy Dark', '#A98204', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3830', 'generic:default', '3830', '3830', 'Terra Cotta', '#BC5544', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3831', 'generic:default', '3831', '3831', 'Raspberry Dark', '#B32F48', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3832', 'generic:default', '3832', '3832', 'Raspberry Medium', '#DB556E', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3833', 'generic:default', '3833', '3833', 'Raspberry Light', '#EA8699', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3834', 'generic:default', '3834', '3834', 'Grape Dark', '#72375D', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3835', 'generic:default', '3835', '3835', 'Grape Medium', '#946083', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3836', 'generic:default', '3836', '3836', 'Grape Light', '#BA91AA', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3837', 'generic:default', '3837', '3837', 'Lavender Ultra Dark', '#6C3A6E', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3838', 'generic:default', '3838', '3838', 'Lavender Blue Dark', '#5C7294', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3839', 'generic:default', '3839', '3839', 'Lavender Blue Medium', '#7B8EAB', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3840', 'generic:default', '3840', '3840', 'Lavender Blue Light', '#B0C0DA', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3841', 'generic:default', '3841', '3841', 'Baby Blue Pale', '#CDDFED', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3842', 'generic:default', '3842', '3842', 'Wedgewood Very Dark', '#32667C', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3843', 'generic:default', '3843', '3843', 'Electric Blue', '#14AAD0', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3844', 'generic:default', '3844', '3844', 'Turquoise Bright Dark', '#12AEBA', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3845', 'generic:default', '3845', '3845', 'Turquoise Bright Medium', '#04C4CA', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3846', 'generic:default', '3846', '3846', 'Turquoise Bright Light', '#06E3E6', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3847', 'generic:default', '3847', '3847', 'Teal Green Dark', '#347D75', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3848', 'generic:default', '3848', '3848', 'Teal Green Medium', '#419392', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3849', 'generic:default', '3849', '3849', 'Teal Green Light', '#52B3AE', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3850', 'generic:default', '3850', '3850', 'Green Bright Dark', '#378477', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3851', 'generic:default', '3851', '3851', 'Green Bright Light', '#49B3A1', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3852', 'generic:default', '3852', '3852', 'Straw Very Dark', '#CD9D37', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3853', 'generic:default', '3853', '3853', 'Autumn Gold Dark', '#F29746', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3854', 'generic:default', '3854', '3854', 'Autumn Gold Medium', '#F2AF68', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3855', 'generic:default', '3855', '3855', 'Autumn Gold Light', '#FAD396', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3856', 'generic:default', '3856', '3856', 'Mahogany Ultra Very Light', '#FFD3B5', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3857', 'generic:default', '3857', '3857', 'Rosewood Dark', '#68251A', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3858', 'generic:default', '3858', '3858', 'Rosewood Medium', '#964A3F', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3859', 'generic:default', '3859', '3859', 'Rosewood Light', '#BA8B7C', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3860', 'generic:default', '3860', '3860', 'Cocoa', '#7D5D57', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3861', 'generic:default', '3861', '3861', 'Cocoa Light', '#A68881', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3862', 'generic:default', '3862', '3862', 'Mocha Beige Dark', '#8A6E4E', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3863', 'generic:default', '3863', '3863', 'Mocha Beige Medium', '#A4835C', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3864', 'generic:default', '3864', '3864', 'Mocha Beige Light', '#CBB69C', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3865', 'generic:default', '3865', '3865', 'Winter White', '#F9F7F1', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:3866', 'generic:default', '3866', '3866', 'Mocha Brown Ultra Very Light', '#FAF6F0', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:B5200', 'generic:default', 'B5200', 'B5200', 'Snow White', '#FFFFFF', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:Ecru', 'generic:default', 'Ecru', 'Ecru', 'Ecru', '#F0EADA', NULL);
INSERT OR IGNORE INTO color (id, line_id, code, full_code, name, hex, status) VALUES ('generic:default:White', 'generic:default', 'White', 'White', 'White', '#FCFBF8', NULL);


